version: '3'
services:
    app: 
        container_name: docker-node-mongo
        restart: always
        build: .
        command: "node app.js"
        ports:
            - '8080:8080'
        depends_on:
            - "mongo"
        networks:
            - wacc

    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
        networks:
            - wacc
            

networks:
    wacc:
        name: wacc-network